Repository jenkinsci/parameterized-scheduler-plugin, pull requests merged in 2020-12, with the labels that each got.

#76 Enable release drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: enhancement

#78 Update pom to latest, baseline to 2.222.4 and use bom to manage deps
  .mvn/extensions.xml
  .mvn/maven.config
Labels: enhancement

#41 Add example of how to set a `parameterizedCron` from pipeline-as-code
  README.md
Labels: documentation

#80 Improve tests and cleanup code
  README.md
  pom.xml
  src/main/java/org/jenkinsci/plugins/parameterizedscheduler/Cron.java
  src/main/java/org/jenkinsci/plugins/parameterizedscheduler/DescriptorImpl.java
  src/main/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterParser.java
  src/main/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterizedCronTab.java
  src/main/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterizedCronTabList.java
  src/main/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterizedTimerTrigger.java
  src/test/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterizedCronTabListTest.java
  src/test/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterizedSchedulerTest.java
Labels: enhancement

#52 Add support for = in parameter values.
  src/main/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterParser.java
  src/test/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterParserTest.java
Labels: enhancement

#81 Point changelog to github releases
  CHANGELOG.md
Labels: documentation

#82 Add build badges to README and a link to the changelog
  README.md
Labels: documentation

#84 [JENKINS-57093] Fix NPE in formvalidation if no job property configured
  src/main/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterParser.java
  src/test/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterParserTest.java
Labels: bug

#85 Improve tests and general cleanup
  src/main/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterParser.java
  src/test/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterParserTest.java
  src/test/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterizedCronTabListTest.java
  src/test/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterizedCronTabTest.java
  src/test/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterizedStaplerRequestTest.java
  src/test/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterizedTimerTriggerCauseTest.java
  src/test/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterizedTimerTriggerTest.java
Labels: chore

#12 Consistent cron argument lines in help detail and README.md
  README.md
  src/main/resources/org/jenkinsci/plugins/parameterizedscheduler/ParameterizedTimerTrigger/help-parameterizedSpecification.html
Labels: documentation

#88 Prevent NPE when createValue returns null
  src/main/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterParser.java
  src/main/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterizedTimerTrigger.java
  src/test/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterizedSchedulerTest.java
Labels: bug

#89 Remove unused structs dependency
  pom.xml
  src/main/java/org/jenkinsci/plugins/parameterizedscheduler/Cron.java
  src/main/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterizedTimerTrigger.java
Labels: dependencies

#90 Change active developer
  pom.xml
Labels: documentation

#91 Warn on parameters without values
  src/main/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterParser.java
  src/main/resources/org/jenkinsci/plugins/parameterizedscheduler/Messages.properties
  src/test/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterParserTest.java
Labels: enhancement
