Repository jenkinsci/parameterized-scheduler-plugin, pull requests merged in 2022-09, with the labels that each got.

#147 Remove upper bound dependency
  pom.xml
Labels: chore

#148 Use the non-deprecated ctor
  src/test/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterizedSchedulerTest.java
Labels: chore

#153 build-user-vars compatibility
  src/main/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterizedTimerTriggerCause.java
  src/test/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterizedTimerTriggerCauseTest.java
Labels: enhancement

#141 Double-% typo in readme
  README.md
Labels: documentation

#154 add permission check and POST annotation
  src/main/java/org/jenkinsci/plugins/parameterizedscheduler/DescriptorImpl.java
Labels: bug

#155 Add java-17 CI
  Jenkinsfile
Labels: chore
